# Generated by Django 5.0.6 on 2025-05-02 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('error', 'Error')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollings', to='bot.bot')),
            ],
        ),
    ]
