# Generated by Django 5.0.6 on 2025-05-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_polling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('training', 'Training'), ('ready', 'Ready'), ('error', 'Error')], max_length=50),
        ),
        migrations.CreateModel(
            name='WhitelistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_domains', to='bot.bot')),
            ],
            options={
                'unique_together': {('bot', 'domain')},
            },
        ),
    ]
